const blogs = [
    {
        id: 1,
        title: "Digital Declutter Cutting the Noise in a Hyperconnected World",
        categories: ["Blog ", "Exploring New Articles", "website"],
        content: "Digital declutter refers to the process of intentionally reducing unnecessary digital interactions and streamlining your digital environment. It’s not just about deleting files or cleaning up your inbox but adopting mindful practices to control how technology integrates into your life. Improved Focus and Productivity Constant notifications and multitasking can fragment attention, reducing the ability to concentrate. Decluttering creates space for deep work Better Mental Health Studies show that excessive screen time and digital overwhelm contribute to anxiety and stress. Simplifying your digital life can lower mental clutter Enhanced Digital Hygiene A clean and organized digital ecosystem protects against security risks and reduces the risk of losing important information.",
        tags: ["Read more"],
        popularity: 8.7,
        isPopular: false,
        isRecent: true,
        date: "2024-10-01",
        image: "/cards/image1.jpg",
        comments: ["Very helpful article!", "Great tips, thanks!"],
    },
    {
        id: 2,
        title: "Eco-Friendly Homes The Future of Real Estate",
        categories: ["Blog ", "Exploring New Articles", "website"],
        content: "Eco-friendly homes are designed and built to minimize energy consumption, reduce waste, and utilize sustainable materials. These homes often incorporate renewable energy sources, efficient water management systems, and environmentally friendly construction practice.",
        tags: ["Read more "],
        popularity: 9.3,
        isPopular: false,
        isRecent: true,
        date: "2024-12-15",
        image: "/cards/image2.png",
        comments: ["Hooks made my life easier!", "Detailed explanation."],
    },
    {
        id: 3,
        title: "A Foodie’s Guide to Europe: Best Culinary Experiences by Country",
        categories: ["Blog ", "Exploring New Articles", "website"],
        content: "Must-Try Dishes: Pizza Margherita, Risotto alla Milanese, and Gelato Signature ExperienceEnjoying fresh pasta in Bologna or a Neapolitan pizza in Naples. Don’t Miss: A vineyard tour in Tuscany to sample Chianti wines",
        tags: ["Read more"],
        popularity: 7.5,
        isPopular: true,
        isRecent: true,
        date: "2024-12-05",
        image: "/cards/image3.png",
        comments: ["This is amazing!"],
    },
    {
        id: 4,
        title: "The Art of Black-and-White Photography",
        content: "Black-and-white photography is a timeless art form that transcends trends and technology. By stripping away color, this medium emphasizes composition, texture, and emotion, creating images that are both powerful and evocative....",
        categories: ["Blog ", "Exploring New Articles", "website"],
        tags: ["Read more "],
        popularity: 9.0,
        isPopular: true,
        isRecent: false,
        date: "2024-09-15",
        image: "/cards/image4.png",
        comments: ["This is amazing!"],
    },
    {
        id: 5,
        title: "Sustainable Travel Tips: Reducing Your Carbon Footprint",
        content: "The hyperconnected world isn’t going anywhere, but its impact on your life is something you can control. By committing to digital declutter, you can cut through the noise, prioritize what matters, and create a healthier, more intentional relationship with technology. Start today and take the first step toward a balanced digital life...",
        categories: ["Blog ", "Exploring New Articles", "website"],
        tags: ["Read more "],
        popularity: 8.2,
        isPopular: false,
        isRecent: true,
        date: "2024-11-30",
        image: "/cards/image5.png",
        comments: ["Informative read."],
    },
    {
        id: 6,
        title: "The Rise of Minimalist Interior Design",
        content: "As technology advances and public awareness grows, the adoption of eco-friendly homes is expected to rise. Governments and developers are increasingly incorporating green building standards, offering incentives, and promoting sustainable communities....",
        categories: ["Blog ", "Exploring New Articles", "website"],
        tags: ["Read more "],
        popularity: 8.9,
        isPopular: true,
        isRecent: false,
        date: "2024-08-10",
        image: "/cards/image6.png",
        comments: ["I needed this guide!"],
    },
    {
        id: 7,
        title: "Crafting a Personal Brand as an Author: Tips for Success",
        content: "As technology advances and public awareness grows, the adoption of eco-friendly homes is expected to rise. Governments and developers are increasingly incorporating green building standards, offering incentives, and promoting sustainable communities...",
        categories: ["Blog ", "Exploring New Articles", "website"],
        tags: ["Read more "],
        popularity: 7.8,
        isPopular: false,
        isRecent: true,
        date: "2024-11-20",
        image: "/cards/image7.png",
        comments: ["Love the insights!", "Very futuristic."],
    },
    {
        id: 8,
        title: "Luxury on a Budget: Affordable High-End Travel Experiences",
        content: "Must-Try Dishes: Coq au Vin, Ratatouille, and Bouillabaisse.Signature Experience: Savoring a croissant and espresso at a Parisian café or dining at a Michelin-starred restaurant in Lyon. Don’t Miss: A wine-tasting tour in Bordeaux or Champagne....",
        categories: ["Blog ", "Exploring New Articles", "website"],
        tags: ["Read more "],
        popularity: 8.3,
        isPopular: false,
        isRecent: false,
        date: "2024-07-20",
        image: "/cards/image8.png",
        comments: ["Very clear examples.", "Great starter guide!"],
    },
    {
        id: 9,
        title: "Cultural Journeys: Exploring the Rich Heritage of Asia",
        content: "Environmental Impact Buildings account for a significant portion of global energy use and greenhouse gas emissions. Eco-friendly homes help reduce this footprint. Cost Savings: Energy-efficient designs and renewable energy sources, like solar panels, lower utility bills in the long run. Healthier Living Spaces:Use of non-toxic materials and improved indoor air quality create a healthier environment for occupants.Future-Proof Investment:As governments and societies push for greener initiatives, eco-friendly homes are likely to increase in value and demand...",
        categories: ["Blog ", "Exploring New Articles", "website"],
        tags: ["Read more "],
        popularity: 7.9,
        isPopular: false,
        isRecent: true,
        date: "2024-11-10",
        image: "/cards/image9.png",
        comments: ["Very exciting topic!"],
    },
    {
        id: 10,
        title: "A Food Lover’s Journey: Top Culinary Destinations Around the World",
        content: "Must-Try Dishes: Bratwurst, Sauerbraten, and Pretzels Signature Experience: Attending Oktoberfest in Munich or exploring the Christmas markets for seasonal treats. Don’t Miss: Sampling craft beers in Berlin’s burgeoning brewery scene....",
        categories: ["Blog ", "Exploring New Articles", "website"],
        tags: ["Read more "],
        popularity: 8.4,
        isPopular: true,
        isRecent: false,
        date: "2024-08-25",
        image: "/cards/image10.png",
        comments: ["Helpful tutorial."],
    },
    {
        id: 11,
        title: "Ultimate Guide to Solo Travel: Tips and Tricks for Every Adventurer",
        content: "Eco-friendly homes are not just a trend but a necessity for a sustainable future. They offer numerous benefits, from reducing environmental impact to providing healthier living spaces and long-term cost savings. As the real estate industry evolves, eco-friendly homes will undoubtedly play a pivotal role in shaping the future of housing....",
        categories: ["Blog ", "Exploring New Articles", "website"],
        tags: ["Read more "],
        popularity: 8.5,
        isPopular: true,
        isRecent: true,
        date: "2024-11-25",
        image: "/cards/image11.png",
        comments: ["Love the clear explanations."],
    },
    {
        id: 12,
        title: "Overcoming Writer's Block: Strategies for Personal Authors",
        content: "Black-and-white photography challenges photographers to think beyond color and focus on the essence of their subjects. By mastering this art form, you can create images that are not only visually compelling but also deeply meaningful. Pick up your camera, embrace the shades of gray, and start your journey into the world of black-and-white photography today....",
        categories: ["Blog ", "Exploring New Articles", "website"],
        tags: ["Read more "],
        popularity: 8.8,
        isPopular: true,
        isRecent: false,
        date: "2024-10-22",
        image: "/cards/image12.png",
        comments: ["Very informative guide."],
    },
    {
        id: 13,
        title: "The Art of Writing: How Personal Authors Find Inspiration Everywhere",
        content: "As technology advances and public awareness grows, the adoption of eco-friendly homes is expected to rise. Governments and developers are increasingly incorporating green building standards, offering incentives, and promoting sustainable communities....",
        categories: ["Blog ", "Exploring New Articles", "website"],
        tags: ["Read more "],
        popularity: 8.9,
        isPopular: false,
        isRecent: true,
        date: "2024-12-10",
        image: "/cards/image13.png",
        comments: ["Super helpful!"],
    },
    {
        id: 14,
        title: "TThe Journey of a Personal Author: Crafting Stories and Buildings",
        content: "Digital declutter is not a one-time task but an ongoing practice. Regularly review your habits and tools to ensure they align with your personal and professional goals. Celebrate small wins, such as reclaiming an hour of productive time or experiencing reduced stress....",
        categories: ["Blog ", "Exploring New Articles", "website"],
        tags: ["Read more "],
        popularity: 9.2,
        isPopular: true,
        isRecent: false,
        date: "2024-08-30",
        image: "/cards/image14.png",
        comments: ["Very comprehensive!"],
    },
    {
        id: 15,
        title: "Adventure Awaits: The Best National Parks to Visit in 2025",
        content: "Each country in Europe offers a unique culinary adventure, blending tradition and innovation. Whether you’re sipping wine in Tuscany, enjoying tapas in Seville, or savoring pastries in Paris, Europe’s diverse food culture ensures an unforgettable journey for every foodie. Bon appétit!..",
        categories: ["Blog ", "Exploring New Articles", "website"],
        tags: ["Read more "],
        popularity: 9.1,
        isPopular: false,
        isRecent: true,
        date: "2024-12-05",
        image: "/cards/image15.png",
        comments: ["This is amazing!"],
    },
    {
        id: 16,
        title: "Island Escapes: The Most Beautiful Islands to Visit in 2025",
        content: "Must-Try Dishes: Paella, Jamón Ibérico, and Gazpacho Signature Experience: A tapas crawl in Seville or tasting pintxos in the Basque Country Don’t Miss: Experiencing a traditional flamenco dinner show.",
        categories: ["Blog ", "Exploring New Articles", "website"],
        tags: ["Read more "],
        popularity: 8.3,
        isPopular: false,
        isRecent: false,
        date: "2024-07-15",
        image: "/cards/image16.png",
        comments: ["This is amazing!"],
    },
    {
        id: 17,
        title: "Mastering Night Photography: Capturing the Beauty of Darkness",
        content: "Black-and-white photography challenges photographers to think beyond color and focus on the essence of their subjects. By mastering this art form, you can create images that are not only visually compelling but also deeply meaningful. Pick up your camera, embrace the shades of gray, and start your journey into the world of black-and-white photography today....",
        categories: ["Blog ", "Exploring New Articles", "website"],
        tags: ["Read more "],
        popularity: 8.0,
        isPopular: true,
        isRecent: true,
        date: "2024-11-18",
        image: "/cards/image17.png",
        comments: ["This is amazing!"],
    },
    {
        id: 18,
        title: "Chasing Sunsets: The World’s Most Scenic Destinations",
        content: "Must-Try Dishes: Coq au Vin, Ratatouille, and Bouillabaisse. Signature Experience: Savoring a croissant and espresso at a Parisian café or dining at a Michelin-starred restaurant in Lyon. Don’t Miss: A wine-tasting tour in Bordeaux or Champagne...",
        categories: ["Blog ", "Exploring New Articles", "website"],
        tags: ["Read more "],
        popularity: 8.7,
        isPopular: true,
        isRecent: false,
        date: "2024-09-25",
        image: "/cards/image18.png",
        comments: ["wow great"],
    },
    {
        id: 19,
        title: "Hidden Gems: Europe’s Best Kept Secret Destinations",
        content: "Timeless Aesthetic:Black-and-white images possess a classic and enduring quality that color photographs often lack.Focus on Composition:Without the distraction of color, elements such as shape, contrast, and light take center stage.Enhanced Emotional Impact:The absence of color allows viewers to focus on the subject’s emotions and the story being told....",
        categories: ["Blog ", "Exploring New Articles", "website"],
        tags: ["Read more "],
        popularity: 8.4,
        isPopular: false,
        isRecent: true,
        date: "2024-11-02",
        image: "/cards/image19.png",
        comments: ["Amazing "],
    },
    {
        id: 20,
        title: "Luxury on a Budget: Affordable High-End Travel Experiences",
        content: "Each country in Europe offers a unique culinary adventure, blending tradition and innovation. Whether youre sipping wine in Tuscany, enjoying tapas in Seville, or savoring pastries in Paris, Europes diverse food culture ensures an unforgettable journey for every foodie. Bon appétit!...",
        categories: ["Blog ", "Exploring New Articles", "website"],
        tags: ["Read more "],
        popularity: 8.6,
        isPopular: false,
        isRecent: false,
        date: "2024-06-10",
        image: "/cards/image20.png",
        comments: ["This is amazing!"],
    },
];

export default blogs;









